# Copyright 2023-2026 Ant Investor Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include: package:lints/recommended.yaml

analyzer:
  errors:
    # Generated code produces these warnings
    annotate_overrides: ignore
    camel_case_types: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    unnecessary_import: ignore
    depend_on_referenced_packages: ignore
    implementation_imports: ignore
    unintended_html_in_doc_comment: ignore
