# Configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/ for details

version: 2.0

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Errorf  # ✅ `errcheck` supports settings

run:
  timeout: 5m

linters:
  disable:
    - gocritic
    - godox
  enable:
    - bidichk
    - durationcheck
    - errcheck
    - errorlint
    - goconst
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ineffassign
    - govet
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - usetesting
    - copyloopvar

issues:
  fix: true
