// Copyright 2023-2026 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package client

// Initiation statuses returned by pawaPay when creating deposits, payouts and refunds.
const (
	InitiationStatusAccepted         = "ACCEPTED"
	InitiationStatusRejected         = "REJECTED"
	InitiationStatusDuplicateIgnored = "DUPLICATE_IGNORED"
)

// Final and transient payment statuses returned by status checks and callbacks.
const (
	PaymentStatusAccepted         = "ACCEPTED"
	PaymentStatusEnqueued         = "ENQUEUED"
	PaymentStatusProcessing       = "PROCESSING"
	PaymentStatusInReconciliation = "IN_RECONCILIATION"
	PaymentStatusCompleted        = "COMPLETED"
	PaymentStatusFailed           = "FAILED"
)

// Search result statuses for status check endpoints.
const (
	SearchStatusFound    = "FOUND"
	SearchStatusNotFound = "NOT_FOUND"
)

// Credentials holds the per-request credentials for pawaPay API calls.
// These can be resolved from queue message headers or fall back to config.
type Credentials struct {
	// APIToken is the pawaPay API bearer token.
	APIToken string
	// Environment selects the API host: sandbox or production.
	Environment string
	// BaseURL overrides the environment-derived API host when set (used in tests).
	BaseURL string
	// Provider is an optional default provider code (e.g. MTN_MOMO_ZMB) used
	// when a payment does not specify one. When empty, the provider is
	// predicted from the phone number.
	Provider string
	// Country is an optional default ISO 3166-1 alpha-3 country code.
	Country string
	// SignatureKeyID is the key identifier used in RFC-9421 request signing.
	// When both SignatureKeyID and PrivateKeyPEM are set, financial POST
	// requests are signed with the ECDSA-P256 key before sending.
	SignatureKeyID string
	// PrivateKeyPEM is the PEM-encoded ECDSA P-256 private key used for
	// RFC-9421 request signing. Accepts PKCS#8 ("PRIVATE KEY") and
	// SEC1 ("EC PRIVATE KEY") PEM blocks. Optional; only used when
	// SignatureKeyID is also set.
	PrivateKeyPEM string
}

// ResolveBaseURL returns the pawaPay API base URL for these credentials.
func (c *Credentials) ResolveBaseURL() string {
	if c.BaseURL != "" {
		return c.BaseURL
	}
	if c.Environment == "production" {
		return "https://api.pawapay.io"
	}
	return "https://api.sandbox.pawapay.io"
}

// FailureReason describes why a payment was rejected or failed.
type FailureReason struct {
	FailureCode    string `json:"failureCode"`
	FailureMessage string `json:"failureMessage"`
}

// AccountDetails identifies a mobile money account.
type AccountDetails struct {
	PhoneNumber string `json:"phoneNumber"`
	Provider    string `json:"provider"`
}

// PayerOrRecipient describes the customer paying or receiving a payment.
// Only type MMO (mobile money) is currently supported by pawaPay.
type PayerOrRecipient struct {
	Type           string         `json:"type"`
	AccountDetails AccountDetails `json:"accountDetails"`
}

// NewMMOParty builds an MMO payer/recipient from a phone number and provider.
func NewMMOParty(phoneNumber, provider string) *PayerOrRecipient {
	return &PayerOrRecipient{
		Type: "MMO",
		AccountDetails: AccountDetails{
			PhoneNumber: phoneNumber,
			Provider:    provider,
		},
	}
}

// Metadata is the pawaPay request metadata format: a list of single-field
// objects, each optionally flagged as PII. Up to 10 fields are allowed.
type Metadata []map[string]any

// BuildMetadata converts a plain map into the pawaPay request metadata format.
// Empty values are omitted.
func BuildMetadata(fields map[string]string) Metadata {
	if len(fields) == 0 {
		return nil
	}
	md := make(Metadata, 0, len(fields))
	for k, v := range fields {
		if v == "" {
			continue
		}
		md = append(md, map[string]any{k: v})
	}
	if len(md) == 0 {
		return nil
	}
	return md
}

// DepositRequest initiates a deposit (collection) from a customer.
type DepositRequest struct {
	// DepositID is a UUIDv4 unique ID generated by the caller for reconciliation.
	DepositID string
	// Amount is a decimal string, e.g. "15" or "123.45". Leading zeroes and
	// trailing decimal zeroes are not permitted by pawaPay.
	Amount string
	// Currency is the ISO 4217 currency code, e.g. ZMW.
	Currency string
	// PhoneNumber is the customer MSISDN (digits only, with country code).
	PhoneNumber string
	// Provider is the mobile money operator code, e.g. MTN_MOMO_ZMB.
	Provider string
	// PreAuthorisationCode is the OTP for providers with authType PREAUTH.
	PreAuthorisationCode string
	// ClientReferenceID links the deposit to an entity in our system.
	ClientReferenceID string
	// CustomerMessage is a 4-22 char alphanumeric narration shown to the customer.
	CustomerMessage string
	// Metadata is attached to the payment and echoed back in callbacks.
	Metadata map[string]string
}

type depositInitiationPayload struct {
	DepositID            string            `json:"depositId"`
	Amount               string            `json:"amount"`
	Currency             string            `json:"currency"`
	Payer                *PayerOrRecipient `json:"payer"`
	PreAuthorisationCode string            `json:"preAuthorisationCode,omitempty"`
	ClientReferenceID    string            `json:"clientReferenceId,omitempty"`
	CustomerMessage      string            `json:"customerMessage,omitempty"`
	Metadata             Metadata          `json:"metadata,omitempty"`
}

// DepositInitiationResponse is the response for an initiated deposit.
type DepositInitiationResponse struct {
	DepositID     string         `json:"depositId"`
	Status        string         `json:"status"`
	Created       string         `json:"created"`
	FailureReason *FailureReason `json:"failureReason,omitempty"`
}

// Deposit is the full deposit representation used by status checks and callbacks.
type Deposit struct {
	DepositID             string            `json:"depositId"`
	Status                string            `json:"status"`
	Amount                string            `json:"amount"`
	Currency              string            `json:"currency"`
	Country               string            `json:"country"`
	Payer                 *PayerOrRecipient `json:"payer"`
	CustomerMessage       string            `json:"customerMessage"`
	ClientReferenceID     string            `json:"clientReferenceId"`
	Created               string            `json:"created"`
	ProviderTransactionID string            `json:"providerTransactionId"`
	FailureReason         *FailureReason    `json:"failureReason,omitempty"`
	Metadata              map[string]any    `json:"metadata,omitempty"`
}

// DepositStatusResult is the response of the check deposit status endpoint.
type DepositStatusResult struct {
	Status string   `json:"status"` // FOUND or NOT_FOUND
	Data   *Deposit `json:"data,omitempty"`
}

// PayoutRequest initiates a payout (disbursement) to a customer.
type PayoutRequest struct {
	// PayoutID is a UUIDv4 unique ID generated by the caller for reconciliation.
	PayoutID string
	// Amount is a decimal string, e.g. "15" or "123.45".
	Amount string
	// Currency is the ISO 4217 currency code, e.g. ZMW.
	Currency string
	// PhoneNumber is the recipient MSISDN (digits only, with country code).
	PhoneNumber string
	// Provider is the mobile money operator code, e.g. MTN_MOMO_ZMB.
	Provider string
	// ClientReferenceID links the payout to an entity in our system.
	ClientReferenceID string
	// CustomerMessage is a 4-22 char alphanumeric narration shown to the customer.
	CustomerMessage string
	// Metadata is attached to the payment and echoed back in callbacks.
	Metadata map[string]string
}

type payoutInitiationPayload struct {
	PayoutID          string            `json:"payoutId"`
	Amount            string            `json:"amount"`
	Currency          string            `json:"currency"`
	Recipient         *PayerOrRecipient `json:"recipient"`
	ClientReferenceID string            `json:"clientReferenceId,omitempty"`
	CustomerMessage   string            `json:"customerMessage,omitempty"`
	Metadata          Metadata          `json:"metadata,omitempty"`
}

// PayoutInitiationResponse is the response for an initiated payout.
type PayoutInitiationResponse struct {
	PayoutID      string         `json:"payoutId"`
	Status        string         `json:"status"`
	Created       string         `json:"created"`
	FailureReason *FailureReason `json:"failureReason,omitempty"`
}

// Payout is the full payout representation used by status checks and callbacks.
type Payout struct {
	PayoutID              string            `json:"payoutId"`
	Status                string            `json:"status"`
	Amount                string            `json:"amount"`
	Currency              string            `json:"currency"`
	Country               string            `json:"country"`
	Recipient             *PayerOrRecipient `json:"recipient"`
	CustomerMessage       string            `json:"customerMessage"`
	ClientReferenceID     string            `json:"clientReferenceId"`
	Created               string            `json:"created"`
	ProviderTransactionID string            `json:"providerTransactionId"`
	FailureReason         *FailureReason    `json:"failureReason,omitempty"`
	Metadata              map[string]any    `json:"metadata,omitempty"`
}

// PayoutStatusResult is the response of the check payout status endpoint.
type PayoutStatusResult struct {
	Status string  `json:"status"` // FOUND or NOT_FOUND
	Data   *Payout `json:"data,omitempty"`
}

// RefundRequest initiates a refund of a completed deposit.
type RefundRequest struct {
	// RefundID is a UUIDv4 unique ID generated by the caller for reconciliation.
	RefundID string
	// DepositID is the pawaPay deposit being refunded.
	DepositID string
	// Amount optionally refunds a partial amount; when empty the full deposit
	// amount is refunded.
	Amount string
	// Currency is the ISO 4217 currency code of the amount.
	Currency string
	// ClientReferenceID links the refund to an entity in our system.
	ClientReferenceID string
	// Metadata is attached to the payment and echoed back in callbacks.
	Metadata map[string]string
}

type refundInitiationPayload struct {
	RefundID          string   `json:"refundId"`
	DepositID         string   `json:"depositId"`
	Amount            string   `json:"amount,omitempty"`
	Currency          string   `json:"currency,omitempty"`
	ClientReferenceID string   `json:"clientReferenceId,omitempty"`
	Metadata          Metadata `json:"metadata,omitempty"`
}

// RefundInitiationResponse is the response for an initiated refund.
type RefundInitiationResponse struct {
	RefundID      string         `json:"refundId"`
	Status        string         `json:"status"`
	Created       string         `json:"created"`
	FailureReason *FailureReason `json:"failureReason,omitempty"`
}

// Refund is the full refund representation used by status checks and callbacks.
type Refund struct {
	RefundID              string            `json:"refundId"`
	Status                string            `json:"status"`
	Amount                string            `json:"amount"`
	Currency              string            `json:"currency"`
	Country               string            `json:"country"`
	Recipient             *PayerOrRecipient `json:"recipient"`
	CustomerMessage       string            `json:"customerMessage"`
	Created               string            `json:"created"`
	ProviderTransactionID string            `json:"providerTransactionId"`
	FailureReason         *FailureReason    `json:"failureReason,omitempty"`
	Metadata              map[string]any    `json:"metadata,omitempty"`
}

// RefundStatusResult is the response of the check refund status endpoint.
type RefundStatusResult struct {
	Status string  `json:"status"` // FOUND or NOT_FOUND
	Data   *Refund `json:"data,omitempty"`
}

// ManualActionResponse is the response for resend-callback and
// fail-enqueued operations across deposits, payouts and refunds.
type ManualActionResponse struct {
	DepositID     string         `json:"depositId,omitempty"`
	PayoutID      string         `json:"payoutId,omitempty"`
	RefundID      string         `json:"refundId,omitempty"`
	Status        string         `json:"status"`
	FailureReason *FailureReason `json:"failureReason,omitempty"`
}

// PaymentPageRequest creates a hosted Payment Page session.
type PaymentPageRequest struct {
	// DepositID is a UUIDv4 unique ID generated by the caller for reconciliation.
	DepositID string
	// ReturnURL is where the customer is redirected after payment processing.
	ReturnURL string
	// Amount and Currency optionally fix the amount on the page.
	Amount   string
	Currency string
	// PhoneNumber optionally prefills the customer phone number.
	PhoneNumber string
	// Language of the page: EN or FR.
	Language string
	// Country optionally restricts payment to phone numbers of one country.
	Country string
	// Reason is shown to the customer to specify what they are paying for.
	Reason string
	// CustomerMessage is a 4-22 char alphanumeric narration shown to the customer.
	CustomerMessage string
	// Metadata is attached to the payment and echoed back in callbacks.
	Metadata map[string]string
}

type amountDetailsPayload struct {
	Amount   string `json:"amount"`
	Currency string `json:"currency"`
}

type paymentPagePayload struct {
	DepositID       string                `json:"depositId"`
	ReturnURL       string                `json:"returnUrl"`
	CustomerMessage string                `json:"customerMessage,omitempty"`
	AmountDetails   *amountDetailsPayload `json:"amountDetails,omitempty"`
	PhoneNumber     string                `json:"phoneNumber,omitempty"`
	Language        string                `json:"language,omitempty"`
	Country         string                `json:"country,omitempty"`
	Reason          string                `json:"reason,omitempty"`
	Metadata        Metadata              `json:"metadata,omitempty"`
}

// PaymentPageSession holds the redirect URL for a created Payment Page session.
// The URL is valid for 15 minutes.
type PaymentPageSession struct {
	RedirectURL string `json:"redirectUrl"`
}

// ProviderPrediction is the result of the predict-provider toolkit endpoint.
type ProviderPrediction struct {
	Country     string `json:"country"`
	Provider    string `json:"provider"`
	PhoneNumber string `json:"phoneNumber"`
}

// WalletBalance is the balance of a single pawaPay wallet.
type WalletBalance struct {
	Country  string `json:"country"`
	Balance  string `json:"balance"`
	Currency string `json:"currency"`
	Provider string `json:"provider"`
}

// WalletBalances is the response of the wallet-balances endpoint.
type WalletBalances struct {
	Balances []WalletBalance `json:"balances"`
}

// OperationConfig describes the limits and behaviour of one operation type
// for a provider currency in the active configuration.
type OperationConfig struct {
	MinAmount        string `json:"minAmount"`
	MaxAmount        string `json:"maxAmount"`
	DecimalsInAmount string `json:"decimalsInAmount"` // TWO_PLACES or NONE
	Status           string `json:"status"`           // OPERATIONAL, DELAYED or CLOSED
	CallbackURL      string `json:"callbackUrl"`
	AuthType         string `json:"authType"`  // deposits: PROVIDER_AUTH, PREAUTH or REDIRECT_AUTH
	PinPrompt        string `json:"pinPrompt"` // deposits: AUTOMATIC or MANUAL
}

// CurrencyConfig describes a currency supported by a provider in the active configuration.
type CurrencyConfig struct {
	Currency       string                     `json:"currency"`
	DisplayName    string                     `json:"displayName"`
	OperationTypes map[string]OperationConfig `json:"operationTypes"`
}

// ProviderConfig describes a provider configured for the account.
type ProviderConfig struct {
	Provider                string           `json:"provider"`
	DisplayName             string           `json:"displayName"`
	NameDisplayedToCustomer string           `json:"nameDisplayedToCustomer"`
	Currencies              []CurrencyConfig `json:"currencies"`
}

// CountryConfig describes a country configured for the account.
type CountryConfig struct {
	Country   string           `json:"country"`
	Prefix    string           `json:"prefix"`
	Providers []ProviderConfig `json:"providers"`
}

// SignatureConfiguration describes the account's request/callback signing setup.
type SignatureConfiguration struct {
	SignedRequestsOnly bool `json:"signedRequestsOnly"`
	SignedCallbacks    bool `json:"signedCallbacks"`
}

// ActiveConfiguration is the response of the active-conf toolkit endpoint.
type ActiveConfiguration struct {
	CompanyName            string                 `json:"companyName"`
	SignatureConfiguration SignatureConfiguration `json:"signatureConfiguration"`
	Countries              []CountryConfig        `json:"countries"`
}

// OperationAvailability is the status of one operation type for a provider.
type OperationAvailability struct {
	OperationType string `json:"operationType"`
	Status        string `json:"status"` // OPERATIONAL, DELAYED or CLOSED
}

// ProviderAvailability is the availability of a single provider.
type ProviderAvailability struct {
	Provider       string                  `json:"provider"`
	OperationTypes []OperationAvailability `json:"operationTypes"`
}

// CountryAvailability is the availability of all providers in a country.
type CountryAvailability struct {
	Country   string                 `json:"country"`
	Providers []ProviderAvailability `json:"providers"`
}
