// Copyright 2023-2026 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package observability defines the OTel instruments for the billing service.
// Instruments are created through frame's telemetry factories so every
// measurement transparently carries tenant_id and partition_id derived from
// the context's security claims.
package observability

import (
	"context"
	"time"

	"github.com/pitabwire/frame/telemetry"
	"go.opentelemetry.io/otel/trace"
)

const pkgName = "service_payment_billing"

// Metrics holds pre-allocated OTel instruments for the billing service.
type Metrics struct {
	tracer telemetry.Tracer

	// Subscription instruments.
	subscriptionsCreated   telemetry.Counter
	subscriptionsCancelled telemetry.Counter

	// Invoice instruments.
	invoicesGenerated telemetry.Counter
	invoicesIssued    telemetry.Counter
	invoicesVoided    telemetry.Counter
	invoicePayments   telemetry.Counter
	invoiceLatency    telemetry.Histogram

	// Billing run instruments.
	billingRunsStarted   telemetry.Counter
	billingRunsCompleted telemetry.Counter
	billingRunLatency    telemetry.Histogram

	// Charge instruments.
	chargesProcessed telemetry.Counter
	chargeLatency    telemetry.Histogram
}

// NewMetrics creates and registers all OTel instruments for the billing service.
// The OTel SDK deduplicates instruments by name so multiple constructions are safe.
func NewMetrics() *Metrics {
	t := telemetry.NewTracer(pkgName)
	bm := telemetry.NewBusinessMetrics(pkgName)

	return &Metrics{
		tracer: t,

		subscriptionsCreated: bm.Counter(
			pkgName+"/subscriptions_created_total",
			"Subscriptions created",
		),
		subscriptionsCancelled: bm.Counter(
			pkgName+"/subscriptions_cancelled_total",
			"Subscriptions cancelled",
		),

		invoicesGenerated: bm.Counter(
			pkgName+"/invoices_created_total",
			"Invoices generated by billing runs",
		),
		invoicesIssued: bm.Counter(
			pkgName+"/invoices_issued_total",
			"Invoices transitioned to issued state",
		),
		invoicesVoided: bm.Counter(
			pkgName+"/invoices_voided_total",
			"Invoices voided",
		),
		invoicePayments: bm.Counter(
			pkgName+"/invoice_payments_recorded_total",
			"Payments recorded against invoices",
		),
		invoiceLatency: bm.Histogram(
			pkgName+"/invoice_generation_latency_ms",
			"Latency distribution of invoice generation",
		),

		billingRunsStarted: bm.Counter(
			pkgName+"/billing_runs_started_total",
			"Billing runs initiated",
		),
		billingRunsCompleted: bm.Counter(
			pkgName+"/billing_runs_completed_total",
			"Billing runs completed successfully",
		),
		billingRunLatency: bm.Histogram(
			pkgName+"/billing_run_latency_ms",
			"Latency distribution of full billing pipeline runs",
		),

		chargesProcessed: bm.Counter(
			pkgName+"/charges_processed_total",
			"Charge events processed",
		),
		chargeLatency: bm.Histogram(
			pkgName+"/charge_latency_ms",
			"Latency distribution of charge processing",
		),
	}
}

// StartSpan starts a new traced span and returns the enriched context and span.
func (m *Metrics) StartSpan(
	ctx context.Context,
	name string,
	opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
	return m.tracer.Start(ctx, name, opts...)
}

// EndSpan ends a span and records any error on it.
func (m *Metrics) EndSpan(ctx context.Context, span trace.Span, err error) {
	m.tracer.End(ctx, span, err)
}

// RecordSubscriptionCreated counts a subscription creation.
func (m *Metrics) RecordSubscriptionCreated(ctx context.Context) {
	if m == nil {
		return
	}
	m.subscriptionsCreated.Add(ctx, 1)
}

// RecordSubscriptionCancelled counts a subscription cancellation.
func (m *Metrics) RecordSubscriptionCancelled(ctx context.Context) {
	if m == nil {
		return
	}
	m.subscriptionsCancelled.Add(ctx, 1)
}

// RecordInvoiceGenerated counts and records latency for invoice generation.
func (m *Metrics) RecordInvoiceGenerated(ctx context.Context, elapsed time.Duration) {
	if m == nil {
		return
	}
	m.invoicesGenerated.Add(ctx, 1)
	m.invoiceLatency.Record(ctx, float64(elapsed.Milliseconds()))
}

// RecordInvoiceIssued counts an invoice transition to issued state.
func (m *Metrics) RecordInvoiceIssued(ctx context.Context) {
	if m == nil {
		return
	}
	m.invoicesIssued.Add(ctx, 1)
}

// RecordInvoiceVoided counts an invoice voiding.
func (m *Metrics) RecordInvoiceVoided(ctx context.Context) {
	if m == nil {
		return
	}
	m.invoicesVoided.Add(ctx, 1)
}

// RecordInvoicePayment counts a payment recorded against an invoice.
func (m *Metrics) RecordInvoicePayment(ctx context.Context) {
	if m == nil {
		return
	}
	m.invoicePayments.Add(ctx, 1)
}

// RecordBillingRunStarted counts a billing run initiation.
func (m *Metrics) RecordBillingRunStarted(ctx context.Context) {
	if m == nil {
		return
	}
	m.billingRunsStarted.Add(ctx, 1)
}

// RecordBillingRunCompleted counts a successfully completed billing run and records its latency.
func (m *Metrics) RecordBillingRunCompleted(ctx context.Context, elapsed time.Duration) {
	if m == nil {
		return
	}
	m.billingRunsCompleted.Add(ctx, 1)
	m.billingRunLatency.Record(ctx, float64(elapsed.Milliseconds()))
}

// RecordChargeProcessed counts a charge event and records its latency.
func (m *Metrics) RecordChargeProcessed(ctx context.Context, elapsed time.Duration) {
	if m == nil {
		return
	}
	m.chargesProcessed.Add(ctx, 1)
	m.chargeLatency.Record(ctx, float64(elapsed.Milliseconds()))
}
