service:
  name: service_jenga_api
  version: "1.0"

http:
  port: 8080

redis:
  addr: "redis:6379"  # Use internal Docker network port
  password: ""
  db: 0

events:
  type: "redis"
  redis:
    addr: "redis:6379"  # Use internal Docker network port
    password: ""
    db: 0
