service:
  name: service_jenga_api
  version: "1.0"

http:
  port: 8080
  tls:
    enabled: false  # Disable TLS for local development

redis:
  addr: "redis:6379"  # Use internal Docker network port
  password: ""
  db: 0

jenga:
  api_key: "${JENGA_API_KEY}"
  consumer_secret: "${JENGA_CONSUMER_SECRET}"
  merchant_code: "${JENGA_MERCHANT_CODE}"
  env: "https://uat.finserve.africa"  # Keep HTTPS for Jenga API

events:
  type: "redis"
  redis:
    addr: "redis:6379"
    password: ""
    db: 0
