version: '3.8'

networks:
  jenga_network:
    driver: bridge

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"   # client port
      - "8222:8222"   # monitoring port
    networks:
      - jenga_network
    restart: unless-stopped
    env_file:
      - .env
    # pass credentials from .env into the NATS server
    command: >-
      --user ${NATS_USER} --pass ${NATS_PASSWORD}

  jenga_service:
    build:
      context: ./
      no_cache: true
    ports:
      - "8080:8080"
    depends_on:
      - payment_service
      - nats-server
    networks:
      - jenga_network
    env_file:
      - .env
    environment:
      - PAYMENT_SERVICE_ENDPOINT=payment_service:50051
      - CALLBACK_URL=https://jenga_service.chamamobile.com/receivepayments
      # include user/pass in the URL
      - NATS_URL=nats://${NATS_USER}:${NATS_PASSWORD}@nats-server:4222?subject=initiate.prompt
      - SKIP_NATS=false
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./keys:/app/keys
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - jenga_service
    networks:
      - jenga_network

  payment_db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: service_payment
      POSTGRES_USER: ant
      POSTGRES_PASSWORD: secret
    ports:
      - "5436:5432"
    networks:
      - jenga_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ant -d service_payment"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment_service:
    build: ../../
    ports:
      - "50051:50051"
    depends_on:
      payment_db:
        condition: service_healthy
      nats-server:
        condition: service_started
    networks:
      - jenga_network
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://ant:secret@payment_db:5432/service_payment?sslmode=disable
      - SECURELY_RUN_SERVICE=false
      - JENGA_API_ENDPOINT=https://jenga_service.chamamobile.com/payments/stk-ussd
      - JENGA_API_TOKEN=${JENGA_API_TOKEN}
      - NATS_URL=nats://${NATS_USER}:${NATS_PASSWORD}@nats-server:4222?subject=initiate.prompt
      - SKIP_NATS=false
    restart: unless-stopped
