version: '3.8'

services:
  jenga_service:
    build: ./
    ports:
      - "8080:8080"  # Map the port where the http server listens
    environment:
      - JENGA_API_KEY=r/PSfbyIYe/0epGhnawG1+g96mHA5zRtQaFc54ySQWAJIMyoLLDZSczc9h/gVrIHreueBDU2kRqH7clhMDEA9Q==
      - JENGA_ENV=uat.finserve.africa
      - JENGA_MERCHANT_CODE=8503993262
      - JENGA_CONSUMER_SECRET=iS3N5hDNwGK3Zm9F1eJ2Aic64e4da8
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - CONFIG_FILE=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6380"  # Changed host port to 6380
    command: redis-server --appendonly yes
    restart: unless-stopped
