networks:
  jenga_network:  # Define a custom network
    driver: bridge
  common_network:
    driver: bridge

services:
  jenga_service:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./keys:/app/keys

    restart: unless-stopped
    network_mode: host

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - jenga_service
    network_mode: host
