name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [apps/default, apps/integrations/jenga-api]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          args: --timeout=5m
          skip-cache: false
          working-directory: ${{ matrix.module }}
